name: todo_list
description: "A mobile application to complement the website created in MERN Stack"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.2
  flutter_native_splash: ^2.4.5
  http: ^1.3.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  intl: ^0.20.2
  sticky_headers: ^0.3.0+2

  # whenever flutter clean is used, type flutter pub run flutter_native_splash:create in terminal so that the splash page is always created

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#07396A" # Change this to your splash screen background color
  image: assets/images/todo-list-transparent-bg-loading-screen.png
  android_12:
    color: "#07396A" # Same as above
    image: assets/images/todo-list-transparent-bg-loading-screen.png